### ISSUE TITLE
Running excel_picks.py on 2016 week 1 data causes pandas exception

### ISSUE THREAD

**Issue by blreams** [blreams/collegefootballpick10#104]
```
(cdcpool)18:28 ~/collegefootballpick10 (master)$ python excel_picks.py 2016 1
Traceback (most recent call last):
  File "excel_picks.py", line 145, in <module>
    create_picks_sheet(year,week_number,data)
  File "excel_picks.py", line 121, in create_picks_sheet
    picks_df[player.ss_name] = column_data
  File "/home/collegefootballpick10/.virtualenvs/cdcpool/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2127, in __setitem__
    self._set_item(key, value)
  File "/home/collegefootballpick10/.virtualenvs/cdcpool/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2204, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/collegefootballpick10/.virtualenvs/cdcpool/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2362, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/home/collegefootballpick10/.virtualenvs/cdcpool/local/lib/python2.7/site-packages/pandas/core/series.py", line 2579, in _sanitize_index
    raise ValueError('Length of values does not match length of '
ValueError: Length of values does not match length of index
```

I haven't tried to use this utility for a while, but I was hoping to use it as a means of backing up the db in preparation for migrating to django 1.10.

**Comment by blreams** [comment]
I took a quick look at this and made a fix to insure it works for Players who did not make picks for the week.
