### ISSUE TITLE
Email pick reminder script appears to not have run successfully

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#120]
Looking at the most recent log for the email reminder script, I see the following

```
Finding players with no picks for 2016 week 9
Traceback (most recent call last):
  File "/home/collegefootballpick10/collegefootballpick10/email_players_with_no_picks.py", line 173, in <module>
    send_admin_email(year,week,deadline)
  File "/home/collegefootballpick10/collegefootballpick10/email_players_with_no_picks.py", line 141, in send_admin_email
    example_subject, example_message = get_reminder_email_text(year,week,deadline,players[0])
  File "/home/collegefootballpick10/collegefootballpick10/email_players_with_no_picks.py", line 97, in get_reminder_email_text
    deadline_str = deadline_as_string(deadline,player.timezone)
  File "/home/collegefootballpick10/collegefootballpick10/email_players_with_no_picks.py", line 89, in deadline_as_string
    tz = pytz.timezone(timezone)
NameError: global name 'pytz' is not defined

2016-10-27 18:02:48 -- Completed task, took 63.00 seconds, return code was 1.
```

I assume this error is related to the recent refactoring.  Also, I see the following in the schedule tab.  I'm not sure what the expiry means.

![screen shot 2016-10-28 at 1 36 00 pm](https://cloud.githubusercontent.com/assets/1541768/19816071/bdfb009e-9d13-11e6-9945-e30dfc6a0b03.png)

**Comment by blreams** [comment]
I actually fixed this earlier today (and committed the fix). It was another case of pytz not imported.

I also extended the expiry to 11/25, which won't quite get us to the end of the season...i guess it depends on what the pick deadline is for the final week.
