### ISSUE TITLE
test_views.py unit test fails

### ISSUE THREAD

**Issue by jbholden** [blreams/collegefootballpick10#52]
The page accessed for the url / was recently changed form index to home.

```Python
-    url(r'^$', 'pick10.views.index', name='index'),
+    url(r'^$', 'pick10.views.home', name='home'),
```

As a result, the unit test in pick10/tests/test_views.py now fails.
```
======================================================================
FAIL: test_index_view_renders_index_template (pick10.tests.test_views.HomeViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Brent/Projects/collegefootballpick10/pick10/tests/test_views.py", line 15, in test_index_view_renders_index_template
    self.assertTemplateUsed(response, 'pick10/index.html')
  File "/Users/Brent/Projects/collegefootballpick10/venv/lib/python2.7/site-packages/django/test/testcases.py", line 542, in assertTemplateUsed
    (template_name, ', '.join(template_names)))
AssertionError: Template 'pick10/index.html' was not a template used to render the response. Actual template(s) used: pick10/home.html, base.html
```

**Comment by blreams** [comment]
I committed a fix for this issue to master.
